import {
  AbstractSchemaArtifact,
  BiboStatus,
  CedarArtifactId,
  CedarUser,
  IsoDate,
  PavVersion,
  SchemaVersion,
} from 'cedar-model-typescript-library';
import { ArtifactMetadata } from '../../models/types';

const TEMPLATE_IRI_PREFIX = 'https://repo.metadatacenter.org/templates/';

const FIELD_IRI_PREFIX = 'https://repo.metadatacenter.org/template-fields/';

const PROPERTY_IRI_PREFIX = 'https://schema.metadatacenter.org/properties/';

/**
 * The JSON-schema title and description CEDAR derives from an artifact's name.
 *
 * A CEDAR artifact is also a JSON Schema document, whose meta-schema requires a
 * non-empty `title`. The name is the only thing an author gives us, so the pair
 * is composed from it — in exactly the words the model library's YAML reader
 * composes them in, which is what lets the same template written as JSON and as
 * YAML read back identically. The serializer this replaces wrote neither, so its
 * output was not a valid JSON Schema.
 */
export function derivedTitle(name: string, kind: 'template' | 'element' | 'field'): string {
  return `${name} ${kind} schema`;
}

export function derivedDescription(name: string, kind: 'template' | 'element' | 'field'): string {
  return `${derivedTitle(name, kind)} generated by the CEDAR Artifact Library`;
}

/** Lifecycle values are carried explicitly instead of being regenerated by field builders. */
export function artifactMetadataOf(field: AbstractSchemaArtifact): ArtifactMetadata {
  return {
    title: field.title,
    description: field.description,
    schemaVersion: field.schema_schemaVersion.getValue(),
    version: field.pav_version.getValue(),
    publicationStatus: field.bibo_status.getJsonValue(),
    createdOn: field.pav_createdOn.getValue(),
    createdBy: field.pav_createdBy.getValue(),
    modifiedOn: field.pav_lastUpdatedOn.getValue(),
    modifiedBy: field.oslc_modifiedBy.getValue(),
    derivedFrom: field.pav_derivedFrom.getValue(),
    previousVersion: field.pav_previousVersion.getValue(),
  };
}

export function applyArtifactMetadata(field: AbstractSchemaArtifact, metadata: ArtifactMetadata): void {
  field.title = metadata.title;
  field.description = metadata.description;
  field.schema_schemaVersion = SchemaVersion.forValue(metadata.schemaVersion);
  field.pav_version = PavVersion.forValue(metadata.version);
  field.bibo_status = BiboStatus.forJsonValue(metadata.publicationStatus);
  field.pav_createdOn = IsoDate.forValue(metadata.createdOn);
  field.pav_createdBy = CedarUser.forValue(metadata.createdBy);
  field.pav_lastUpdatedOn = IsoDate.forValue(metadata.modifiedOn);
  field.oslc_modifiedBy = CedarUser.forValue(metadata.modifiedBy);
  field.pav_derivedFrom = CedarArtifactId.forValue(metadata.derivedFrom);
  field.pav_previousVersion = CedarArtifactId.forValue(metadata.previousVersion);
}

/**
 * The identifiers a field keeps for as long as it exists.
 *
 * Minted once, when the author adds the field, and stored in the designer's
 * state. The serializer used to mint them on every call, so the same template
 * exported twice carried different identifiers and a host listening for changes
 * was told the whole artifact was new on every keystroke. Identity is a property
 * of the field, not of the act of writing it down.
 */
export function newFieldIdentity(): { atId: string; propertyIri: string } {
  return {
    atId: `${FIELD_IRI_PREFIX}${crypto.randomUUID()}`,
    propertyIri: `${PROPERTY_IRI_PREFIX}${crypto.randomUUID()}`,
  };
}

/** A template identifier for a template that does not have one yet. */
export function newTemplateIdentifier(): string {
  return `${TEMPLATE_IRI_PREFIX}${crypto.randomUUID()}`;
}
