/**
 * The editor's state, as a CEDAR template.
 *
 * Everything about what a CEDAR template is belongs to
 * `@org.metadatacenter/cedar-model-typescript-library`, which builds the model,
 * writes it as JSON or YAML and reads either back. This file is the translation
 * between that model and the flat `Field` list the editor holds while an author
 * is working, and it is deliberately the only place in the application that
 * mentions the library.
 *
 * It replaces a hand-written serializer that spelled the CEDAR vocabulary out in
 * object literals and shipped a YAML emitter and parser of its own. That code
 * dropped the recommended status, the multiple-values flag, default values and
 * every controlled-term constraint, minted a new identifier and timestamp on each
 * call, and could not read anything it had not written.
 */
import {
  AbstractDynamicChildDeploymentInfo,
  AbstractDynamicChildDeploymentInfoBuilder,
  BiboStatus,
  BioportalTermType,
  CedarBuilders,
  CedarFieldType,
  CedarReaders,
  CedarWriters,
  ControlledTermBranchBuilder,
  ControlledTermClassBuilder,
  ControlledTermField,
  ControlledTermOntologyBuilder,
  ControlledTermValueSetBuilder,
  ChildDeploymentInfo,
  ChildDeploymentInfoBuilder,
  Iri,
  JsonNode,
  SchemaVersion,
  Template,
  TemplateField,
  TemporalField,
  TemporalGranularity,
  TemporalType,
} from 'cedar-model-typescript-library';
import { ControlledTermConfig, Field } from '../models/types';

/**
 * What a field builder is, for our purposes.
 *
 * The library exports every concrete builder but not the `TemplateFieldBuilder`
 * base they share, so the common setters are named here rather than reached for
 * through a cast at each call. The per-type additions — options, temporal
 * settings, controlled-term constraints — are narrowed where they are used,
 * because a text field genuinely has no `addRadioOption`.
 */
type FieldBuilder = {
  withTitle(title: string | null): FieldBuilder;
  withDescription(description: string | null): FieldBuilder;
  withSchemaName(name: string | null): FieldBuilder;
  withSchemaDescription(description: string | null): FieldBuilder;
  withSchemaVersion(version: SchemaVersion): FieldBuilder;
  withStatus(status: BiboStatus): FieldBuilder;
  withAtId(atId: string): FieldBuilder;
  build(): TemplateField;
};

const TEMPLATE_IRI_PREFIX = 'https://repo.metadatacenter.org/templates/';
const FIELD_IRI_PREFIX = 'https://repo.metadatacenter.org/template-fields/';
const PROPERTY_IRI_PREFIX = 'https://schema.metadatacenter.org/properties/';

/**
 * The JSON-schema title and description CEDAR derives from an artifact's name.
 *
 * A CEDAR artifact is also a JSON Schema document, whose meta-schema requires a
 * non-empty `title`. The name is the only thing an author gives us, so the pair
 * is composed from it — in exactly the words the model library's YAML reader
 * composes them in, which is what lets the same template written as JSON and as
 * YAML read back identically. The serializer this replaces wrote neither, so its
 * output was not a valid JSON Schema.
 */
function derivedTitle(name: string, kind: 'template' | 'field'): string {
  return `${name} ${kind} schema`;
}

function derivedDescription(name: string, kind: 'template' | 'field'): string {
  return `${derivedTitle(name, kind)} generated by the CEDAR Artifact Library`;
}

/** The template as the editor holds it, before it is a CEDAR artifact. */
export interface EditorTemplate {
  name: string;
  description: string;
  identifier: string;
  version: string;
  fields: Field[];
}

/**
 * The identifiers a field keeps for as long as it exists.
 *
 * Minted once, when the author adds the field, and stored in editor state. The
 * serializer used to mint them on every call, so the same template exported twice
 * carried different identifiers and a host listening for changes was told the
 * whole artifact was new on every keystroke. Identity is a property of the field,
 * not of the act of writing it down.
 */
export function newFieldIdentity(): { atId: string; propertyIri: string } {
  return {
    atId: `${FIELD_IRI_PREFIX}${crypto.randomUUID()}`,
    propertyIri: `${PROPERTY_IRI_PREFIX}${crypto.randomUUID()}`,
  };
}

/** A template identifier for a template that does not have one yet. */
export function newTemplateIdentifier(): string {
  return `${TEMPLATE_IRI_PREFIX}${crypto.randomUUID()}`;
}

/**
 * The editor's field types, as CEDAR's.
 *
 * `image` is the loosest of these. The editor offers it as a file upload and
 * CEDAR has no such field, so it maps to the static image field, which displays
 * one. Worth revisiting when the editor's own field list is next examined.
 */
const FIELD_BUILDERS: Record<string, () => FieldBuilder> = {
  text: () => CedarBuilders.textFieldBuilder(),
  paragraph: () => CedarBuilders.textAreaBuilder(),
  multipleChoice: () => CedarBuilders.radioFieldBuilder(),
  checkboxes: () => CedarBuilders.checkboxFieldBuilder(),
  date: () => CedarBuilders.temporalFieldBuilder(),
  time: () => CedarBuilders.temporalFieldBuilder(),
  email: () => CedarBuilders.emailFieldBuilder(),
  link: () => CedarBuilders.linkFieldBuilder(),
  phone: () => CedarBuilders.phoneNumberFieldBuilder(),
  number: () => CedarBuilders.numericFieldBuilder(),
  image: () => CedarBuilders.imageFieldBuilder(),
  orcid: () => CedarBuilders.extOrcidFieldBuilder(),
  controlledTerms: () => CedarBuilders.controlledTermFieldBuilder(),
};

/** The reverse, for reading a template back into editor state. */
const EDITOR_TYPES: Array<[CedarFieldType, string]> = [
  [CedarFieldType.TEXT, 'text'],
  [CedarFieldType.TEXTAREA, 'paragraph'],
  [CedarFieldType.RADIO, 'multipleChoice'],
  [CedarFieldType.CHECKBOX, 'checkboxes'],
  [CedarFieldType.EMAIL, 'email'],
  [CedarFieldType.LINK, 'link'],
  [CedarFieldType.PHONE_NUMBER, 'phone'],
  [CedarFieldType.NUMERIC, 'number'],
  [CedarFieldType.STATIC_IMAGE, 'image'],
  [CedarFieldType.EXT_ORCID, 'orcid'],
  [CedarFieldType.CONTROLLED_TERM, 'controlledTerms'],
];

/**
 * The key a field is deployed under, which must be unique within the template.
 *
 * The field's name, because that is what a CEDAR author sees in the artifact and
 * what the corpus uses. Names are not unique in the editor, so a repeat takes a
 * numeric suffix: the serializer used the raw name and two fields called "Title"
 * silently became one.
 */
function deploymentKeys(fields: Field[]): string[] {
  const used = new Set<string>();
  return fields.map((field, index) => {
    const base = field.name.trim() || `field_${index + 1}`;
    let key = base;
    let suffix = 2;
    while (used.has(key)) {
      key = `${base} ${suffix}`;
      suffix += 1;
    }
    used.add(key);
    return key;
  });
}

function buildTemporal(builder: FieldBuilder, editorType: string): void {
  const temporal = builder as unknown as {
    withTemporalType(type: TemporalType): unknown;
    withTemporalGranularity(granularity: TemporalGranularity): unknown;
  };
  if (editorType === 'time') {
    temporal.withTemporalType(TemporalType.TIME);
    temporal.withTemporalGranularity(TemporalGranularity.MINUTE);
  } else {
    temporal.withTemporalType(TemporalType.DATE);
    temporal.withTemporalGranularity(TemporalGranularity.DAY);
  }
}

function buildOptions(builder: FieldBuilder, field: Field): void {
  const withOptions = builder as unknown as {
    addRadioOption?(label: string): unknown;
    addOption?(label: string): unknown;
  };
  for (const option of field.options) {
    if (withOptions.addRadioOption) {
      withOptions.addRadioOption(option);
    } else if (withOptions.addOption) {
      withOptions.addOption(option);
    }
  }
}

/**
 * The constraints an author chose in the controlled-term panel.
 *
 * One constraint per field, because that is all the panel collects: it asks for a
 * source type and then for one source of that type. CEDAR allows several of each
 * kind on one field, which is what the picker will offer when it replaces the
 * panel.
 */
function buildControlledTerm(builder: FieldBuilder, config: ControlledTermConfig | undefined): void {
  if (!config) {
    return;
  }
  const controlled = builder as unknown as {
    addOntology(o: unknown): unknown;
    addBranch(b: unknown): unknown;
    addClass(c: unknown): unknown;
    addValueSet(v: unknown): unknown;
  };

  switch (config.sourceType) {
    case 'ontology':
      if (config.ontologyId) {
        controlled.addOntology(
          new ControlledTermOntologyBuilder()
            .withUri(new Iri(config.ontologyId))
            .withAcronym(config.sourceId ?? '')
            .withName(config.ontologyName ?? '')
            .build(),
        );
      }
      break;
    case 'ontology-branch':
      if (config.branchRootId) {
        controlled.addBranch(
          new ControlledTermBranchBuilder()
            .withUri(new Iri(config.branchRootId))
            .withSource(config.sourceId ?? '')
            .withAcronym(config.sourceId ?? '')
            .withName(config.branchRootName ?? '')
            .withMaxDepth(config.searchDepth ?? 1)
            .build(),
        );
      }
      break;
    case 'ontology-term':
      if (config.sourceId) {
        controlled.addClass(
          new ControlledTermClassBuilder()
            .withUri(new Iri(config.sourceId))
            .withSource(config.ontologyId ?? '')
            .withType(BioportalTermType.ONTOLOGY_CLASS)
            .withLabel(config.sourceName ?? '')
            .withPrefLabel(config.sourceName ?? '')
            .build(),
        );
      }
      break;
    case 'value-set':
      if (config.sourceId) {
        controlled.addValueSet(
          new ControlledTermValueSetBuilder()
            .withUri(new Iri(config.sourceId))
            .withVsCollection(config.ontologyId ?? '')
            .withName(config.sourceName ?? '')
            .build(),
        );
      }
      break;
  }
}

function buildField(field: Field): TemplateField {
  const builder = (FIELD_BUILDERS[field.type] ?? FIELD_BUILDERS['text'])();

  builder
    .withTitle(derivedTitle(field.name, 'field'))
    .withDescription(derivedDescription(field.name, 'field'))
    .withSchemaName(field.name)
    /*
     * Null rather than an empty string when there is no help text. The two mean
     * the same thing, but only one survives both serializations: the YAML writer
     * omits an empty description and the YAML reader returns null for a missing
     * one, so writing `''` made a template read back differently depending on
     * which format it had been written in.
     */
    .withSchemaDescription(field.helpText || null)
    .withSchemaVersion(SchemaVersion.CURRENT)
    .withStatus(BiboStatus.DRAFT);

  if (field.atId) {
    builder.withAtId(field.atId);
  }

  if (field.type === 'date' || field.type === 'time') {
    buildTemporal(builder, field.type);
  }
  if (field.type === 'multipleChoice' || field.type === 'checkboxes') {
    buildOptions(builder, field);
  }
  if (field.type === 'controlledTerms') {
    buildControlledTerm(builder, field.controlledTermConfig);
  }
  if (field.defaultValue) {
    const withDefault = builder as unknown as { withDefaultValue?(value: string): unknown };
    withDefault.withDefaultValue?.(field.defaultValue);
  }

  return builder.build();
}

/** The editor's state, as a CEDAR template. */
export function buildTemplate(state: EditorTemplate): Template {
  const builder = CedarBuilders.templateBuilder()
    .withAtId(state.identifier || newTemplateIdentifier())
    .withTitle(derivedTitle(state.name, 'template'))
    .withDescription(derivedDescription(state.name, 'template'))
    .withSchemaName(state.name)
    .withSchemaDescription(state.description)
    .withSchemaVersion(SchemaVersion.CURRENT)
    .withVersion(state.version || '0.0.1')
    .withStatus(BiboStatus.DRAFT);

  const keys = deploymentKeys(state.fields);
  state.fields.forEach((field, index) => {
    const built = buildField(field);
    const deployment = built.createDeploymentBuilder(keys[index]) as AbstractDynamicChildDeploymentInfoBuilder;
    deployment.withRequiredValue(field.status === 'required').withRecommendedValue(field.status === 'recommended');
    if (field.propertyIri) {
      deployment.withIri(field.propertyIri);
    }
    /*
     * Only where the type leaves the choice open. A checkbox and a multiple-choice
     * list are multiple by their type and a radio is single by its, so their
     * deployment builders have no flag to set — the library models that by giving
     * them a different builder rather than by ignoring the call.
     */
    if (deployment instanceof ChildDeploymentInfoBuilder) {
      deployment.withMultiInstance(field.allowMultiple);
    }
    builder.addChild(built, deployment.build() as ChildDeploymentInfo);
  });

  return builder.build();
}

/**
 * How one child is deployed in its template.
 *
 * The container types its children as `AbstractChildDeploymentInfo`, which is the
 * base every child shares and carries none of the settings a field deployment
 * has. Every child the designer writes is a field, so the narrowing is safe here
 * and belongs here rather than at each call site.
 */
export function fieldDeployment(template: Template, key: string): AbstractDynamicChildDeploymentInfo | null {
  const info = template.getChildrenInfo().get(key);
  return info === null ? null : (info as AbstractDynamicChildDeploymentInfo);
}

export function templateToJson(template: Template): JsonNode {
  return CedarWriters.json().getStrict().getTemplateWriter().getAsJsonNode(template);
}

export function templateToYaml(template: Template, isCompact = false): string {
  return CedarWriters.yaml().getStrict().getTemplateWriter().getAsYamlString(template, isCompact);
}

/**
 * A template from JSON or YAML, in either case as the same model.
 *
 * Throws on a source that is not a template. The editor used to swallow that:
 * `loadTemplate` caught the parse failure, logged it and returned, leaving the
 * author looking at their previous template with no indication that the file they
 * opened had not been read.
 */
export function readTemplate(source: string | object): Template {
  if (typeof source !== 'string') {
    return CedarReaders.json()
      .getStrict()
      .getTemplateReader()
      .readFromObject(source as JsonNode).template;
  }

  const trimmed = source.trim();
  if (trimmed.startsWith('{')) {
    return CedarReaders.json().getStrict().getTemplateReader().readFromString(trimmed).template;
  }

  const template = CedarReaders.yaml().getStrict().getTemplateReader().readFromString(trimmed).template;
  if (template.getChildrenInfo().children.length === 0 && !template.schema_name) {
    throw new Error('The source is not a CEDAR template.');
  }
  return template;
}

function editorTypeOf(field: TemplateField): string {
  const match = EDITOR_TYPES.find(([cedarType]) => cedarType === field.cedarFieldType);
  if (match) {
    return match[1];
  }
  if (field.cedarFieldType === CedarFieldType.TEMPORAL) {
    return (field as TemporalField).valueConstraints.temporalType === TemporalType.TIME ? 'time' : 'date';
  }
  return 'text';
}

function optionsOf(field: TemplateField): string[] {
  const literals = (field as unknown as { valueConstraints?: { literals?: Array<{ label: string }> } }).valueConstraints
    ?.literals;
  return literals ? literals.map((literal) => literal.label) : [];
}

function controlledTermConfigOf(field: TemplateField): ControlledTermConfig | undefined {
  if (field.cedarFieldType !== CedarFieldType.CONTROLLED_TERM) {
    return undefined;
  }
  const constraints = (field as ControlledTermField).valueConstraints;

  const branch = constraints.branches[0];
  if (branch) {
    return {
      sourceType: 'ontology-branch',
      sourceId: branch.acronym,
      ontologyName: branch.name,
      branchRootId: branch.uri.getValue() ?? '',
      branchRootName: branch.name,
      searchDepth: branch.maxDepth,
    };
  }
  const ontology = constraints.ontologies[0];
  if (ontology) {
    return {
      sourceType: 'ontology',
      sourceId: ontology.acronym,
      ontologyId: ontology.uri.getValue() ?? '',
      ontologyName: ontology.name,
    };
  }
  const cls = constraints.classes[0];
  if (cls) {
    return {
      sourceType: 'ontology-term',
      sourceId: cls.uri.getValue() ?? '',
      sourceName: cls.prefLabel,
      ontologyId: cls.source,
    };
  }
  const valueSet = constraints.valueSets[0];
  if (valueSet) {
    return {
      sourceType: 'value-set',
      sourceId: valueSet.uri.getValue() ?? '',
      sourceName: valueSet.name,
      ontologyId: valueSet.vsCollection,
    };
  }
  return undefined;
}

/** A parsed template, as the flat state the editor works in. */
export function toEditorTemplate(template: Template): EditorTemplate {
  const fields: Field[] = [];

  template.getChildrenInfo().children.forEach((info, index) => {
    const field = template.getField(info.name);
    if (field === null) {
      return;
    }
    const dynamic = info as AbstractDynamicChildDeploymentInfo;
    const defaultValue = (field as unknown as { valueConstraints?: { defaultValue?: unknown } }).valueConstraints
      ?.defaultValue;

    fields.push({
      id: index + 1,
      type: editorTypeOf(field),
      name: field.schema_name ?? info.name,
      status: dynamic.requiredValue ? 'required' : dynamic.recommendedValue ? 'recommended' : 'optional',
      options: optionsOf(field),
      defaultValue: typeof defaultValue === 'string' ? defaultValue : '',
      allowMultiple: info instanceof ChildDeploymentInfo ? info.multiInstance : info.isMultiInAnyWay(),
      helpText: field.schema_description ?? '',
      atId: field.at_id?.getValue() ?? undefined,
      propertyIri: dynamic.iri ?? undefined,
      controlledTermConfig: controlledTermConfigOf(field),
    });
  });

  return {
    name: template.schema_name ?? '',
    description: template.schema_description ?? '',
    identifier: template.at_id?.getValue() ?? '',
    version: template.pav_version?.getValue() ?? '0.0.1',
    fields,
  };
}
