/**
 * The designer's state, as a CEDAR template.
 *
 * Everything about what a CEDAR template is belongs to
 * `@org.metadatacenter/cedar-model-typescript-library`, which builds the model,
 * writes it as JSON or YAML and reads either back. This file is the translation
 * between that model and the flat `Field` list the designer holds while an author
 * is working, and it is deliberately the only place in the application that
 * mentions the library.
 *
 * It replaces a hand-written serializer that spelled the CEDAR vocabulary out in
 * object literals and shipped a YAML emitter and parser of its own. That code
 * dropped the recommended status, the multiple-values flag, default values and
 * every controlled-term constraint, minted a new identifier and timestamp on each
 * call, and could not read anything it had not written.
 */
import {
  PavVersion,
  IsoDate,
  CedarArtifactId,
  CedarUser,
  Annotations,
  AnnotationAtId,
  AnnotationAtValue,
  Language,
  AbstractDynamicChildDeploymentInfo,
  AbstractDynamicChildDeploymentInfoBuilder,
  BiboStatus,
  CedarArtifactType,
  BioportalTermType,
  CedarBuilders,
  CedarFieldType,
  CedarReaders,
  CedarWriters,
  ControlledTermActionBuilder,
  ControlledTermBranchBuilder,
  ControlledTermClassBuilder,
  ControlledTermField,
  ControlledTermOntologyBuilder,
  ControlledTermValueSetBuilder,
  ControlledTermVersion,
  ChildDeploymentInfo,
  ChildDeploymentInfoBuilder,
  ChildDeploymentInfoAlwaysMultipleBuilder,
  Iri,
  JsonNode,
  JsonPath,
  SchemaVersion,
  Template,
  TemplateField,
  TemporalField,
  TemporalGranularity,
  TemporalType,
  TimeFormat,
  NumberType,
  NumericField,
  TextField,
  TextFieldBuilder,
  NumericFieldBuilder,
  TemporalFieldBuilder,
  ControlledTermDefaultValueBuilder,
  ControlledTermFieldBuilder,
  StaticImageFieldBuilder,
  StaticYoutubeFieldBuilder,
  StaticImageField,
  StaticYoutubeField,
  RadioFieldBuilder,
  CheckboxFieldBuilder,
  SingleChoiceListFieldBuilder,
  MultipleChoiceListFieldBuilder,
} from 'cedar-model-typescript-library';
import { ArtifactMetadata, ControlledTermSet, ControlledTermConfig, Field, FieldDefaultValue } from '../models/types';

/**
 * What a field builder is, for our purposes.
 *
 * The library exports every concrete builder but not the `TemplateFieldBuilder`
 * base they share, so the common setters are named here rather than reached for
 * through a cast at each call. The per-type additions — options, temporal
 * settings, controlled-term constraints — are narrowed where they are used,
 * because a text field genuinely has no `addRadioOption`.
 */
type FieldBuilder = {
  withPreferredLabel(label: string | null): FieldBuilder;
  withAlternateLabels(labels: string[] | null): FieldBuilder;
  withSchemaIdentifier(identifier: string | null): FieldBuilder;
  withTitle(title: string | null): FieldBuilder;
  withDescription(description: string | null): FieldBuilder;
  withSchemaName(name: string | null): FieldBuilder;
  withSchemaDescription(description: string | null): FieldBuilder;
  withSchemaVersion(version: SchemaVersion): FieldBuilder;
  withStatus(status: BiboStatus): FieldBuilder;
  withAtId(atId: string): FieldBuilder;
  build(): TemplateField;
};

const TEMPLATE_IRI_PREFIX = 'https://repo.metadatacenter.org/templates/';
const FIELD_IRI_PREFIX = 'https://repo.metadatacenter.org/template-fields/';
const PROPERTY_IRI_PREFIX = 'https://schema.metadatacenter.org/properties/';

/**
 * The JSON-schema title and description CEDAR derives from an artifact's name.
 *
 * A CEDAR artifact is also a JSON Schema document, whose meta-schema requires a
 * non-empty `title`. The name is the only thing an author gives us, so the pair
 * is composed from it — in exactly the words the model library's YAML reader
 * composes them in, which is what lets the same template written as JSON and as
 * YAML read back identically. The serializer this replaces wrote neither, so its
 * output was not a valid JSON Schema.
 */
function derivedTitle(name: string, kind: 'template' | 'field'): string {
  return `${name} ${kind} schema`;
}

function derivedDescription(name: string, kind: 'template' | 'field'): string {
  return `${derivedTitle(name, kind)} generated by the CEDAR Artifact Library`;
}

/** Lifecycle values are carried explicitly instead of being regenerated by field builders. */
function artifactMetadataOf(field: TemplateField): ArtifactMetadata {
  return {
    title: field.title,
    description: field.description,
    schemaVersion: field.schema_schemaVersion.getValue(),
    version: field.pav_version.getValue(),
    publicationStatus: field.bibo_status.getJsonValue(),
    createdOn: field.pav_createdOn.getValue(),
    createdBy: field.pav_createdBy.getValue(),
    modifiedOn: field.pav_lastUpdatedOn.getValue(),
    modifiedBy: field.oslc_modifiedBy.getValue(),
    derivedFrom: field.pav_derivedFrom.getValue(),
    previousVersion: field.pav_previousVersion.getValue(),
  };
}
function applyArtifactMetadata(field: TemplateField, metadata: ArtifactMetadata): void {
  field.title = metadata.title;
  field.description = metadata.description;
  field.schema_schemaVersion = SchemaVersion.forValue(metadata.schemaVersion);
  field.pav_version = PavVersion.forValue(metadata.version);
  field.bibo_status = BiboStatus.forJsonValue(metadata.publicationStatus);
  field.pav_createdOn = IsoDate.forValue(metadata.createdOn);
  field.pav_createdBy = CedarUser.forValue(metadata.createdBy);
  field.pav_lastUpdatedOn = IsoDate.forValue(metadata.modifiedOn);
  field.oslc_modifiedBy = CedarUser.forValue(metadata.modifiedBy);
  field.pav_derivedFrom = CedarArtifactId.forValue(metadata.derivedFrom);
  field.pav_previousVersion = CedarArtifactId.forValue(metadata.previousVersion);
}
export function fieldArtifactMetadata(field: Field): ArtifactMetadata {
  return field.artifact ?? artifactMetadataOf(buildField(field));
}

/** The template as the designer holds it, before it is a CEDAR artifact. */
export interface DesignerTemplate {
  name: string;
  description: string;
  identifier: string;
  version: string;
  fields: Field[];
}

/**
 * The identifiers a field keeps for as long as it exists.
 *
 * Minted once, when the author adds the field, and stored in the designer's
 * state. The serializer used to mint them on every call, so the same template
 * exported twice carried different identifiers and a host listening for changes
 * was told the whole artifact was new on every keystroke. Identity is a property
 * of the field, not of the act of writing it down.
 */
export function newFieldIdentity(): { atId: string; propertyIri: string } {
  return {
    atId: `${FIELD_IRI_PREFIX}${crypto.randomUUID()}`,
    propertyIri: `${PROPERTY_IRI_PREFIX}${crypto.randomUUID()}`,
  };
}

/** A template identifier for a template that does not have one yet. */
export function newTemplateIdentifier(): string {
  return `${TEMPLATE_IRI_PREFIX}${crypto.randomUUID()}`;
}

/**
 * Every field type the designer offers, and what CEDAR makes of it.
 *
 * One descriptor per type, rather than a builder map beside a reverse map that
 * had to be kept in step by hand. `deployment` is the part that is not
 * decoration: a field's deployment builder differs by type, and a static field's
 * does not extend the dynamic one at all, so asking a page break to be required
 * is not a setting that gets ignored — it is a call to a method that is not
 * there. Building an image field threw for exactly that reason.
 *
 * `content` names the one extra value a static field carries: the markup of a
 * rich text block, the URL of an image, the id of a video.
 */
type DeploymentKind = 'plain' | 'alwaysSingle' | 'alwaysMultiple' | 'static';

/**
 * A parameter one kind of field accepts and others do not.
 *
 * Named for what an author sets, not for the method that records it, because the
 * two do not correspond one to one: a numeric field's bounds are two setters and
 * a temporal field's precision is a datatype plus a granularity. The setters each
 * one requires are named by `PARAMETER_SETTERS`, which is what lets a test ask the
 * model library whether a type really accepts what its descriptor claims.
 *
 * The parameters every field carries are not here. A name, a description, an
 * identifier, a status and the provenance stamps belong to the artifact rather
 * than to one kind of field, and the descriptor would say the same thing about
 * every type.
 */
export type FieldParameter =
  | 'textLength'
  | 'textPattern'
  | 'numericBounds'
  | 'numericPrecision'
  | 'numericType'
  | 'numericUnit'
  | 'temporalPrecision'
  | 'temporalTimezone'
  | 'temporalTimeFormat'
  | 'mediaDimensions'
  | 'controlledTermConstraints';

/**
 * The model library setters each parameter is written through, all of which a
 * type's builder must have for the descriptor's claim to hold.
 */
export const PARAMETER_SETTERS: Record<FieldParameter, readonly string[]> = {
  textLength: ['withMinLength', 'withMaxLength'],
  textPattern: ['withRegex'],
  numericBounds: ['withMinValue', 'withMaxValue'],
  numericPrecision: ['withDecimalPlaces'],
  numericType: ['withNumberType'],
  numericUnit: ['withUnitOfMeasure'],
  temporalPrecision: ['withTemporalType', 'withTemporalGranularity'],
  temporalTimezone: ['withTimezoneEnabled'],
  temporalTimeFormat: ['withInputTimeFormat'],
  mediaDimensions: ['withWidth', 'withHeight'],
  controlledTermConstraints: ['addOntology', 'addBranch', 'addClass', 'addValueSet', 'addAction'],
};

interface FieldDescriptor {
  readonly cedarType: CedarFieldType;
  readonly build: () => FieldBuilder;
  readonly deployment: DeploymentKind;
  /** Whether the type takes the author's list of options. */
  readonly options?: (builder: FieldBuilder, label: string, selected: boolean) => unknown;
  readonly defaultKind?: FieldDefaultValue['kind'];
  /** The parameters this type accepts beyond those every field carries. */
  readonly parameters?: readonly FieldParameter[];
  /**
   * Set where the type carries no `_valueConstraints` and `deployment` does not
   * already say so.
   *
   * A static field has none, which `deployment: 'static'` states. An
   * attribute-value field is the one dynamic type with none: CEDAR's meta-schema
   * gives `attributeValueTemplateField.json` no `_valueConstraints` property at
   * all, so the field has nowhere to record a requirement.
   */
  readonly valueConstraints?: false;
  /** What the type's single static value is for, where it has one. */
  readonly content?: 'markup' | 'url' | 'videoId';
}

const FIELD_DESCRIPTORS: Record<string, FieldDescriptor> = {
  text: {
    defaultKind: 'literal',
    cedarType: CedarFieldType.TEXT,
    build: () => CedarBuilders.textFieldBuilder(),
    deployment: 'plain',
    parameters: ['textLength', 'textPattern'],
  },
  paragraph: {
    defaultKind: 'literal',
    cedarType: CedarFieldType.TEXTAREA,
    build: () => CedarBuilders.textAreaBuilder(),
    deployment: 'plain',
  },
  multipleChoice: {
    defaultKind: 'literal',
    cedarType: CedarFieldType.RADIO,
    build: () => CedarBuilders.radioFieldBuilder(),
    deployment: 'alwaysSingle',
    options: (builder, label, selected) => (builder as RadioFieldBuilder).addRadioOption(label, selected),
  },
  checkboxes: {
    defaultKind: 'literals',
    cedarType: CedarFieldType.CHECKBOX,
    build: () => CedarBuilders.checkboxFieldBuilder(),
    deployment: 'alwaysMultiple',
    options: (builder, label, selected) => (builder as CheckboxFieldBuilder).addCheckboxOption(label, selected),
  },
  singleChoiceList: {
    defaultKind: 'literal',
    cedarType: CedarFieldType.SINGLE_SELECT_LIST,
    build: () => CedarBuilders.singleChoiceListFieldBuilder(),
    deployment: 'plain',
    options: (builder, label, selected) => (builder as SingleChoiceListFieldBuilder).addListOption(label, selected),
  },
  multipleChoiceList: {
    defaultKind: 'literals',
    cedarType: CedarFieldType.MULTIPLE_SELECT_LIST,
    build: () => CedarBuilders.multipleChoiceListFieldBuilder(),
    deployment: 'alwaysMultiple',
    options: (builder, label, selected) => (builder as MultipleChoiceListFieldBuilder).addListOption(label, selected),
  },
  date: {
    defaultKind: 'temporal',
    cedarType: CedarFieldType.TEMPORAL,
    build: () => CedarBuilders.temporalFieldBuilder(),
    deployment: 'plain',
    parameters: ['temporalPrecision', 'temporalTimezone', 'temporalTimeFormat'],
  },
  time: {
    defaultKind: 'temporal',
    cedarType: CedarFieldType.TEMPORAL,
    build: () => CedarBuilders.temporalFieldBuilder(),
    deployment: 'plain',
    parameters: ['temporalPrecision', 'temporalTimezone', 'temporalTimeFormat'],
  },
  email: {
    defaultKind: 'literal',
    cedarType: CedarFieldType.EMAIL,
    build: () => CedarBuilders.emailFieldBuilder(),
    deployment: 'plain',
  },
  link: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.LINK,
    build: () => CedarBuilders.linkFieldBuilder(),
    deployment: 'plain',
  },
  phone: {
    defaultKind: 'literal',
    cedarType: CedarFieldType.PHONE_NUMBER,
    build: () => CedarBuilders.phoneNumberFieldBuilder(),
    deployment: 'plain',
  },
  number: {
    defaultKind: 'number',
    cedarType: CedarFieldType.NUMERIC,
    build: () => CedarBuilders.numericFieldBuilder(),
    deployment: 'plain',
    parameters: ['numericBounds', 'numericPrecision', 'numericType', 'numericUnit'],
  },
  controlledTerms: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.CONTROLLED_TERM,
    build: () => CedarBuilders.controlledTermFieldBuilder(),
    deployment: 'plain',
    parameters: ['controlledTermConstraints'],
  },
  attributeValue: {
    cedarType: CedarFieldType.ATTRIBUTE_VALUE,
    build: () => CedarBuilders.attributeValueFieldBuilder(),
    deployment: 'alwaysMultiple',
    valueConstraints: false,
  },

  // The external authorities, which differ from one another only in which
  // register they resolve an identifier against.
  orcid: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.EXT_ORCID,
    build: () => CedarBuilders.extOrcidFieldBuilder(),
    deployment: 'plain',
  },
  ror: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.EXT_ROR,
    build: () => CedarBuilders.extRorFieldBuilder(),
    deployment: 'plain',
  },
  pfas: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.EXT_PFAS,
    build: () => CedarBuilders.extPfasFieldBuilder(),
    deployment: 'plain',
  },
  rrid: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.EXT_RRID,
    build: () => CedarBuilders.extRridFieldBuilder(),
    deployment: 'plain',
  },
  pubmed: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.EXT_PUBMED,
    build: () => CedarBuilders.extPubmedFieldBuilder(),
    deployment: 'plain',
  },
  nihGrantId: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.EXT_NIH_GRANT_ID,
    build: () => CedarBuilders.extNihGrantIdFieldBuilder(),
    deployment: 'plain',
  },
  doi: {
    defaultKind: 'iri',
    cedarType: CedarFieldType.EXT_DOI,
    build: () => CedarBuilders.extDoiFieldBuilder(),
    deployment: 'plain',
  },

  // The static types, which show something rather than collect it.
  image: {
    cedarType: CedarFieldType.STATIC_IMAGE,
    build: () => CedarBuilders.imageFieldBuilder(),
    deployment: 'static',
    content: 'url',
    parameters: ['mediaDimensions'],
  },
  richText: {
    cedarType: CedarFieldType.STATIC_RICH_TEXT,
    build: () => CedarBuilders.richTextFieldBuilder(),
    deployment: 'static',
    content: 'markup',
  },
  youtube: {
    cedarType: CedarFieldType.STATIC_YOUTUBE,
    build: () => CedarBuilders.youtubeFieldBuilder(),
    deployment: 'static',
    content: 'videoId',
    parameters: ['mediaDimensions'],
  },
  sectionBreak: {
    cedarType: CedarFieldType.STATIC_SECTION_BREAK,
    build: () => CedarBuilders.sectionBreakFieldBuilder(),
    deployment: 'static',
  },
  pageBreak: {
    cedarType: CedarFieldType.STATIC_PAGE_BREAK,
    build: () => CedarBuilders.pageBreakFieldBuilder(),
    deployment: 'static',
  },
};

/** The descriptor for a palette type, falling back to text for one we do not know. */
export function descriptorOf(paletteType: string): FieldDescriptor {
  return FIELD_DESCRIPTORS[paletteType] ?? FIELD_DESCRIPTORS['text'];
}

/** Static blocks and attribute-value fields have no default in the model. */
export function allowsDefault(paletteType: string): boolean {
  return descriptorOf(paletteType).defaultKind !== undefined;
}

/**
 * Whether a type accepts a parameter, asked of the descriptor rather than of the
 * type's name.
 *
 * The settings panel and the writer both used to test the name — `type === 'text'`
 * for length and pattern, `'date' || 'time'` for precision, `'image' || 'youtube'`
 * for dimensions. Each such chain is a second place to remember a decision the
 * descriptor already records, and they diverge in the direction that is hardest to
 * notice: a control offered for a type whose builder has no setter behind it
 * writes nothing, and the author is told nothing.
 */
export function accepts(paletteType: string, parameter: FieldParameter): boolean {
  return descriptorOf(paletteType).parameters?.includes(parameter) ?? false;
}

/** Every parameter a type accepts, for a caller enumerating rather than asking. */
export function parametersOf(paletteType: string): readonly FieldParameter[] {
  return descriptorOf(paletteType).parameters ?? [];
}

export function temporalGranularities(type: string) {
  const time = TemporalGranularity.valuesWithTimes();
  const choices =
    type === 'xsd:date'
      ? [TemporalGranularity.YEAR, TemporalGranularity.MONTH, TemporalGranularity.DAY]
      : type === 'xsd:time'
        ? time
        : [TemporalGranularity.DAY, ...time];
  return choices.map((choice) => choice.getValue()!);
}

export const NUMERIC_TYPES = NumberType.values().map((type) => type.getValue()!);

/**
 * Whether a type's author can mark it required or recommended.
 *
 * CEDAR records a requirement in the field's own `_valueConstraints`, so a type
 * that has none cannot carry one. Static fields are one such kind and an
 * attribute-value field is the other, which is why this asks the descriptor
 * rather than asking whether the field is static — the production designer's own
 * table draws the same two distinctions separately, and declares
 * `allowsRequired: false` for `attribute-value` while calling it non-static.
 *
 * The requirement offered on an attribute-value field was not simply ignored,
 * which is what made it worth removing rather than leaving. The JSON writer omits
 * the whole constraints node for that type, so a requirement set in the card
 * vanished; the YAML writer records `required: true` under the child, so it
 * survived. The same template therefore said different things depending on which
 * format it was saved in, and the one the artifact server stores is the one that
 * dropped it. Both model libraries behave this way.
 *
 * This decides what an author may set, not what the designer preserves: a status
 * read from a template is still written back.
 */
export function allowsStatus(paletteType: string): boolean {
  const descriptor = descriptorOf(paletteType);
  return descriptor.deployment !== 'static' && descriptor.valueConstraints !== false;
}

/**
 * Whether a type's author chooses how many values it takes.
 *
 * A radio is single by its type and a checkbox multiple by its, so for those the
 * question is already answered and the control would be a lie.
 */
export function allowsMultiple(paletteType: string): boolean {
  return descriptorOf(paletteType).deployment === 'plain';
}

/** Whether a type carries a list of options its author writes. */
export function allowsOptions(paletteType: string): boolean {
  return descriptorOf(paletteType).options !== undefined;
}

/** What a type's static content is, where it has any. */
export function contentKindOf(paletteType: string): 'markup' | 'url' | 'videoId' | undefined {
  return descriptorOf(paletteType).content;
}

/**
 * The key a field is deployed under, which must be unique within the template.
 *
 * The field's name, because that is what a CEDAR author sees in the artifact and
 * what the corpus uses. Names are not unique in the designer, so a repeat takes a
 * numeric suffix: the serializer used the raw name and two fields called "Title"
 * silently became one.
 */
function deploymentKeys(fields: Field[]): string[] {
  const used = new Set<string>();
  return fields.map((field, index) => {
    const base = field.deploymentName ?? (field.name.trim() || `field_${index + 1}`);
    let key = base;
    let suffix = 2;
    while (used.has(key)) {
      key = `${base} ${suffix}`;
      suffix += 1;
    }
    used.add(key);
    return key;
  });
}

function buildTemporal(builder: FieldBuilder, field: Field): void {
  const paletteType = field.type;
  const temporal = builder as TemporalFieldBuilder;
  if (field.temporal) {
    if (!temporalGranularities(field.temporal.type).includes(field.temporal.granularity))
      throw new Error('The selected precision is incompatible with the temporal datatype.');
    temporal.withTemporalType(TemporalType.forValue(field.temporal.type));
    temporal.withTemporalGranularity(TemporalGranularity.forValue(field.temporal.granularity));
    temporal.withTimezoneEnabled(field.temporal.timezoneEnabled);
    temporal.withInputTimeFormat(TimeFormat.forValue(field.temporal.inputTimeFormat));
    return;
  }
  if (paletteType === 'time') {
    temporal.withTemporalType(TemporalType.TIME);
    temporal.withTemporalGranularity(TemporalGranularity.MINUTE);
  } else {
    temporal.withTemporalType(TemporalType.DATE);
    temporal.withTemporalGranularity(TemporalGranularity.DAY);
  }
}

function buildOptions(builder: FieldBuilder, field: Field): void {
  const selected =
    field.defaultValue.kind === 'literals'
      ? field.defaultValue.values
      : field.defaultValue.kind === 'literal'
        ? [field.defaultValue.value]
        : [];
  const scalar = field.importedChoiceDefault ?? selected.find((value) => !field.options.includes(value));
  if (scalar !== undefined)
    (
      builder as
        RadioFieldBuilder | CheckboxFieldBuilder | SingleChoiceListFieldBuilder | MultipleChoiceListFieldBuilder
    ).withDefaultValue(scalar);
  for (const option of field.options) {
    /*
     * An option the author has not named yet is not an option. Its label is
     * empty because the card seeds a blank and lets the placeholder show the
     * hint, so writing it would put `{"label": ""}` in the artifact.
     */
    if (option.trim() === '') {
      continue;
    }
    descriptorOf(field.type).options!(builder, option, selected.includes(option));
  }
}

/**
 * The constraints an author chose in the controlled-term panel.
 *
 * One constraint per field, because that is all the panel collects: it asks for a
 * source type and then for one source of that type. CEDAR allows several of each
 * kind on one field, which is what the picker will offer when it replaces the
 * panel.
 */
/**
 * The URI CEDAR gives an ontology, from its acronym.
 *
 * An acronym is not a URI, and this was writing one into the URI slot: JSON came
 * out saying `"uri": "DOID"` while the YAML path — which derives the URI from the
 * acronym itself — said `https://data.bioontology.org/ontologies/DOID`. The same
 * template written in the two formats was two different artifacts, and only one
 * of them named an ontology.
 *
 * The base is stated here because the model library derives it internally and
 * exports no constant for it. Anything already absolute is left alone, so a
 * source that arrives with a real URI keeps it.
 */
const BIOPORTAL_ONTOLOGY_BASE = 'https://data.bioontology.org/ontologies/';

function ontologyUri(acronym: string): string {
  return /^https?:\/\//.test(acronym) ? acronym : `${BIOPORTAL_ONTOLOGY_BASE}${acronym}`;
}

function buildControlledTermSet(builder: FieldBuilder, set: ControlledTermSet | undefined): void {
  if (!set) return;
  for (const config of set.constraints) buildControlledTerm(builder, config);
  for (const action of set.actions) {
    (builder as ControlledTermFieldBuilder).addAction(
      new ControlledTermActionBuilder()
        .withAction(action.action)
        .withTo(action.to ?? null)
        .withTermUri(new Iri(action.termUri))
        .withSourceUri(new Iri(action.sourceUri))
        .withSource(action.source)
        .withType(BioportalTermType.forJsonValue(action.type))
        .build(),
    );
  }
}

function buildControlledTerm(builder: FieldBuilder, config: ControlledTermConfig | undefined): void {
  if (!config) {
    return;
  }
  /*
   * The snapshot the author pinned, given to whichever entry is being built. An
   * entry with no version resolves against the latest snapshot the terminology
   * server serves, which is what a null means here rather than an omission.
   */
  const version = config.version
    ? new ControlledTermVersion(
        config.version.id,
        config.version.effectiveDate ?? null,
        config.version.declaredVersion ?? null,
      )
    : null;
  const controlled = builder as unknown as {
    addOntology(o: unknown): unknown;
    addBranch(b: unknown): unknown;
    addClass(c: unknown): unknown;
    addValueSet(v: unknown): unknown;
  };

  switch (config.sourceType) {
    case 'ontology':
      if (config.ontologyId) {
        controlled.addOntology(
          new ControlledTermOntologyBuilder()
            .withVersion(version)
            .withIri(config.iri ? new Iri(config.iri) : null)
            .withSourceSystem(config.sourceSystem ?? null)
            .withUri(new Iri(config.uri ?? ontologyUri(config.ontologyId)))
            .withNumTerms(config.numTerms ?? null)
            .withAcronym(config.ontologyId)
            .withName(config.ontologyName ?? '')
            .build(),
        );
      }
      break;
    case 'ontology-branch':
      if (config.branchRootId) {
        controlled.addBranch(
          new ControlledTermBranchBuilder()
            .withVersion(version)
            .withIri(config.iri ? new Iri(config.iri) : null)
            .withSourceSystem(config.sourceSystem ?? null)
            .withUri(new Iri(config.branchRootId))
            .withSource(config.source ?? config.sourceId ?? '')
            .withAcronym(config.sourceId ?? '')
            .withName(config.branchRootName ?? '')
            .withMaxDepth(config.searchDepth ?? 1)
            .build(),
        );
      }
      break;
    case 'ontology-term':
      if (config.sourceId) {
        controlled.addClass(
          new ControlledTermClassBuilder()
            .withVersion(version)
            .withIri(config.iri ? new Iri(config.iri) : null)
            .withSourceSystem(config.sourceSystem ?? null)
            .withUri(new Iri(config.sourceId))
            .withSource(config.source ?? config.ontologyId ?? '')
            .withType(BioportalTermType.forJsonValue(config.termType ?? 'OntologyClass'))
            .withLabel(config.label ?? config.sourceName ?? '')
            .withPrefLabel(config.sourceName ?? '')
            .build(),
        );
      }
      break;
    case 'value-set':
      if (config.sourceId) {
        controlled.addValueSet(
          new ControlledTermValueSetBuilder()
            .withVersion(version)
            .withIri(config.iri ? new Iri(config.iri) : null)
            .withSourceSystem(config.sourceSystem ?? null)
            .withUri(new Iri(config.sourceId))
            .withNumTerms(config.numTerms ?? null)
            .withVsCollection(config.ontologyId ?? '')
            .withName(config.sourceName ?? '')
            .build(),
        );
      }
      break;
  }
}

/**
 * The one value a static field carries.
 *
 * Three different setters for what is, to an author, the same box: the markup of
 * a rich text block, the address of an image, the id of a video.
 */
function buildStaticContent(builder: FieldBuilder, kind: 'markup' | 'url' | 'videoId', content: string): void {
  if (!content) {
    return;
  }
  const staticBuilder = builder as unknown as {
    withContent?(content: string): unknown;
    withVideoId?(videoId: string): unknown;
  };
  if (kind === 'videoId') {
    staticBuilder.withVideoId?.(content);
  } else {
    staticBuilder.withContent?.(content);
  }
}

function buildField(field: Field): TemplateField {
  if (field.publishedDefinition)
    return CedarReaders.json().getStrict().getTemplateFieldReader().readFromString(field.publishedDefinition).field;
  const descriptor = descriptorOf(field.type);
  const builder = descriptor.build();

  builder
    .withTitle(derivedTitle(field.name, 'field'))
    .withDescription(derivedDescription(field.name, 'field'))
    .withPreferredLabel(field.preferredLabel || null)
    .withAlternateLabels(field.alternateLabels?.length ? field.alternateLabels : null)
    .withSchemaIdentifier(field.schemaIdentifier || null)
    .withSchemaName(field.name)
    /*
     * Null rather than an empty string when there is no help text. The two mean
     * the same thing, but only one survives both serializations: the YAML writer
     * omits an empty description and the YAML reader returns null for a missing
     * one, so writing `''` made a template read back differently depending on
     * which format it had been written in.
     */
    .withSchemaDescription(field.helpText || null)
    .withSchemaVersion(SchemaVersion.CURRENT)
    .withStatus(BiboStatus.DRAFT);

  if (field.atId) {
    builder.withAtId(field.atId);
  }

  if (accepts(field.type, 'temporalPrecision')) {
    buildTemporal(builder, field);
  }
  if (accepts(field.type, 'textLength') && field.textConstraints) {
    const { minLength, maxLength, regex } = field.textConstraints;
    if (
      [minLength, maxLength].some((n) => n !== null && (!Number.isInteger(n) || n < 0)) ||
      (minLength !== null && maxLength !== null && minLength > maxLength)
    ) {
      throw new Error('Text lengths must be nonnegative whole numbers, with minimum no greater than maximum.');
    }
    const pattern = regex ? new RegExp(regex) : null;
    if (field.defaultValue.kind === 'literal') {
      const value = field.defaultValue.value;
      if (
        (minLength !== null && value.length < minLength) ||
        (maxLength !== null && value.length > maxLength) ||
        (pattern && !pattern.test(value))
      )
        throw new Error('The existing default does not satisfy these text constraints. Edit or clear it first.');
    }
    (builder as TextFieldBuilder)
      .withMinLength(field.textConstraints.minLength)
      .withMaxLength(field.textConstraints.maxLength)
      .withRegex(field.textConstraints.regex);
  }
  if (accepts(field.type, 'numericBounds') && field.numeric) {
    const { min, max, decimalPlaces } = field.numeric;
    if ([min, max].some((n) => n !== null && !Number.isFinite(n)) || (min !== null && max !== null && min > max))
      throw new Error('Numeric bounds must be finite, with minimum no greater than maximum.');
    if (decimalPlaces !== null && (!Number.isInteger(decimalPlaces) || decimalPlaces < 0))
      throw new Error('Decimal places must be a nonnegative whole number.');
    const numeric = builder as NumericFieldBuilder;
    numeric
      .withNumberType(NumberType.forValue(field.numeric.type))
      .withMinValue(field.numeric.min)
      .withMaxValue(field.numeric.max)
      .withDecimalPlaces(field.numeric.decimalPlaces)
      .withUnitOfMeasure(field.numeric.unit);
  }
  if (descriptor.options) {
    buildOptions(builder, field);
  }
  if (accepts(field.type, 'controlledTermConstraints')) {
    buildControlledTermSet(builder, field.controlledTermConstraints);
  }
  if (descriptor.content) {
    buildStaticContent(builder, descriptor.content, field.content ?? '');
  }
  if (accepts(field.type, 'mediaDimensions')) {
    for (const dimension of [field.width, field.height]) {
      if (dimension != null && (!Number.isInteger(dimension) || dimension <= 0))
        throw new Error('Media dimensions must be positive whole numbers.');
    }
    (builder as StaticImageFieldBuilder | StaticYoutubeFieldBuilder)
      .withWidth(field.width ?? null)
      .withHeight(field.height ?? null);
  }
  const value = field.defaultValue;
  if (value.kind !== 'none') {
    if (value.kind !== descriptor.defaultKind)
      throw new Error(`A ${field.type} field cannot hold a ${value.kind} default.`);
    if (descriptor.options) {
      const values = value.kind === 'literals' ? value.values : value.kind === 'literal' ? [value.value] : [];
      if (values.filter((option) => !field.options.includes(option)).length > 1)
        throw new Error('Only one scalar choice default can be preserved.');
    } else {
      switch (value.kind) {
        case 'literal':
        case 'temporal':
          (builder as FieldBuilder & { withDefaultValue(value: string): unknown }).withDefaultValue(value.value);
          break;
        case 'number':
          (builder as NumericFieldBuilder).withDefaultValue(value.value);
          break;
        case 'iri':
          // A term default carries a label beside its IRI, and only a type whose
          // values are drawn from a vocabulary has one to carry.
          if (accepts(field.type, 'controlledTermConstraints')) {
            (builder as ControlledTermFieldBuilder).withDefaultValue(
              new ControlledTermDefaultValueBuilder()
                .withTermUri(new Iri(value.iri))
                .withRdfsLabel(value.label ?? '')
                .build(),
            );
          } else {
            (builder as FieldBuilder & { withDefaultValue(value: Iri): unknown }).withDefaultValue(new Iri(value.iri));
          }
          break;
      }
    }
  }

  const built = builder.build();
  if (field.artifact) applyArtifactMetadata(built, field.artifact);
  built.language = Language.forValue(field.language || null);
  if (field.annotations?.length) {
    const annotations = new Annotations();
    for (const annotation of field.annotations) {
      if (!annotation.name.trim()) throw new Error('Each annotation needs a name.');
      if (annotations.get(annotation.name)) throw new Error('Annotation names must be unique.');
      if (annotation.kind === 'iri' && !/^[a-z][a-z0-9+.-]*:\S+$/i.test(annotation.value))
        throw new Error('An annotation IRI must be an absolute identifier.');
      annotations.add(
        annotation.kind === 'iri'
          ? new AnnotationAtId(annotation.name, annotation.value)
          : new AnnotationAtValue(annotation.name, annotation.value),
      );
    }
    built.annotations = annotations;
  }
  return built;
}

/** Validate before changing state; model builders may reject intermediate defaults. */
export function defaultValueError(field: Field, value: FieldDefaultValue): string | null {
  try {
    if (allowsOptions(field.type)) {
      const values = value.kind === 'literal' ? [value.value] : value.kind === 'literals' ? value.values : [];
      if (values.some((option) => !field.options.includes(option))) return 'Choose a default from the field options.';
    }
    buildField({ ...field, defaultValue: value, importedChoiceDefault: undefined });
    return null;
  } catch (error) {
    return error instanceof Error ? error.message : String(error);
  }
}

/** A standalone field artifact, written by the same path used for template children. */
export function fieldToJson(field: Field): JsonNode {
  const built = buildField(field);
  return CedarWriters.json().getStrict().getFieldWriterForField(built).getAsJsonNode(built);
}

/** The designer's state, as a CEDAR template. */
export function buildTemplate(state: DesignerTemplate): Template {
  const builder = CedarBuilders.templateBuilder()
    .withAtId(state.identifier || newTemplateIdentifier())
    .withTitle(derivedTitle(state.name, 'template'))
    .withDescription(derivedDescription(state.name, 'template'))
    .withSchemaName(state.name)
    /*
     * Null rather than an empty string, for the reason the field description is:
     * the YAML writer omits an empty description and the YAML reader returns null
     * for a missing one, so a template with no description read back differently
     * depending on which format it had been written in. Fields were fixed when the
     * library took over serialization; the template's own description was not.
     */
    .withSchemaDescription(state.description || null)
    .withSchemaVersion(SchemaVersion.CURRENT)
    .withVersion(state.version || '0.0.1')
    .withStatus(BiboStatus.DRAFT);

  const keys = deploymentKeys(state.fields);
  state.fields.forEach((field, index) => {
    const built = buildField(field);
    const deployment = built
      .createDeploymentBuilder(keys[index])
      .withLabel(field.displayLabel ?? null)
      .withDescription(field.displayDescription ?? null)
      .withHidden(field.hidden ?? false);

    /*
     * A static field's deployment builder does not extend the dynamic one, so it
     * has no required value, no recommended value and no property IRI — those are
     * not settings it ignores, they are methods it does not have. Building an
     * image field threw here until this branch existed.
     */
    if (deployment instanceof AbstractDynamicChildDeploymentInfoBuilder) {
      deployment.withContinuePreviousLine(field.continuePreviousLine ?? false);
      deployment.withValueRecommendationEnabled(field.valueRecommendationEnabled ?? false);
      deployment.withRequiredValue(field.status === 'required').withRecommendedValue(field.status === 'recommended');
      if (field.propertyIri) {
        deployment.withIri(field.propertyIri);
      }
    }

    /*
     * Only where the type leaves the choice open. A checkbox, an attribute-value
     * field and a multiple-choice list are multiple by their type and a radio is
     * single by its, so their deployment builders have no flag to set — the
     * library models that by giving them a different builder rather than by
     * ignoring the call.
     */
    if (deployment instanceof ChildDeploymentInfoBuilder) {
      deployment.withMultiInstance(field.allowMultiple);
    }
    if (
      deployment instanceof ChildDeploymentInfoAlwaysMultipleBuilder ||
      (deployment instanceof ChildDeploymentInfoBuilder && field.allowMultiple)
    ) {
      const min = field.minItems ?? null;
      const max = field.maxItems ?? null;
      if (
        [min, max].some((value) => value !== null && (!Number.isInteger(value) || value < 0)) ||
        (min !== null && max !== null && min > max)
      ) {
        throw new Error('Occurrence limits must be nonnegative whole numbers, with minimum no greater than maximum.');
      }
      deployment.withMinItems(min).withMaxItems(max);
    }
    builder.addChild(built, deployment.build() as ChildDeploymentInfo);
  });

  return builder.build();
}

/**
 * How one child is deployed in its template.
 *
 * The container types its children as `AbstractChildDeploymentInfo`, which is the
 * base every child shares and carries none of the settings a field deployment
 * has. Every child the designer writes is a field, so the narrowing is safe here
 * and belongs here rather than at each call site.
 */
export function fieldDeployment(template: Template, key: string): AbstractDynamicChildDeploymentInfo | null {
  const info = template.getChildrenInfo().get(key);
  return info === null ? null : (info as AbstractDynamicChildDeploymentInfo);
}

export function templateToJson(template: Template): JsonNode {
  return CedarWriters.json().getStrict().getTemplateWriter().getAsJsonNode(template);
}

export function templateToYaml(template: Template, isCompact = false): string {
  const yaml = CedarWriters.yaml().getStrict().getTemplateWriter().getAsYamlString(template, isCompact);
  if (!isCompact) {
    const restored = CedarReaders.yaml().getStrict().getTemplateReader().readFromString(yaml).template;
    const canonical = (value: unknown): string => {
      if (Array.isArray(value)) return '[' + value.map(canonical).join(',') + ']';
      if (value !== null && typeof value === 'object')
        return (
          '{' +
          Object.entries(value)
            .sort(([a], [b]) => a.localeCompare(b))
            .map(([key, item]) => JSON.stringify(key) + ':' + canonical(item))
            .join(',') +
          '}'
        );
      return JSON.stringify(value);
    };
    if (canonical(templateToJson(template)) !== canonical(templateToJson(restored))) {
      throw new Error(
        'YAML cannot preserve every property of this template, such as custom schema metadata. Export JSON to retain the complete definitions.',
      );
    }
  }
  return yaml;
}

/**
 * A template from JSON or YAML, in either case as the same model.
 *
 * Throws on a source that is not a template. The designer used to swallow that:
 * `loadTemplate` caught the parse failure, logged it and returned, leaving the
 * author looking at their previous template with no indication that the file they
 * opened had not been read.
 */
export function readTemplate(source: string | object): Template {
  if (typeof source !== 'string') {
    return CedarReaders.json()
      .getStrict()
      .getTemplateReader()
      .readFromObject(source as JsonNode).template;
  }

  const trimmed = source.trim();
  if (trimmed.startsWith('{')) {
    return CedarReaders.json().getStrict().getTemplateReader().readFromString(trimmed).template;
  }

  const template = CedarReaders.yaml().getStrict().getTemplateReader().readFromString(trimmed).template;
  if (template.getChildrenInfo().children.length === 0 && !template.schema_name) {
    throw new Error('The source is not a CEDAR template.');
  }
  return template;
}

function paletteTypeOf(field: TemplateField): string {
  /*
   * Temporal first, because two palette types share one CEDAR type and only the
   * value constraints tell them apart. Reading the table would give whichever of
   * the two it lists, which is how a time field came back as a date.
   */
  if (field.cedarFieldType === CedarFieldType.TEMPORAL) {
    return (field as TemporalField).valueConstraints.temporalType === TemporalType.TIME ? 'time' : 'date';
  }
  const match = Object.entries(FIELD_DESCRIPTORS).find(
    ([, descriptor]) => descriptor.cedarType === field.cedarFieldType,
  );
  return match ? match[0] : 'text';
}

/** The static content a field carries, for reading one back into the designer's state. */
function contentOf(field: TemplateField): string | undefined {
  const staticField = field as unknown as { content?: unknown; videoId?: unknown; value?: unknown };
  const value = staticField.videoId ?? staticField.content ?? staticField.value;
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

function optionsOf(field: TemplateField): string[] {
  const literals = (field as unknown as { valueConstraints?: { literals?: Array<{ label: string }> } }).valueConstraints
    ?.literals;
  return literals ? literals.map((literal) => literal.label) : [];
}

/** The snapshot an entry names, as the designer records one. */
function versionRefOf(entry: {
  version?: { id: string; effectiveDate: string | null; declaredVersion: string | null } | null;
}) {
  const version = entry.version;
  if (!version) {
    return undefined;
  }
  return {
    id: version.id,
    effectiveDate: version.effectiveDate ?? undefined,
    declaredVersion: version.declaredVersion ?? undefined,
  };
}

function controlledTermConstraintsOf(field: TemplateField): ControlledTermSet | undefined {
  if (field.cedarFieldType !== CedarFieldType.CONTROLLED_TERM) return undefined;
  const c = (field as ControlledTermField).valueConstraints;
  const common = (
    entry:
      | (typeof c.ontologies)[number]
      | (typeof c.branches)[number]
      | (typeof c.classes)[number]
      | (typeof c.valueSets)[number],
  ) => ({
    iri: entry.iri?.getValue() ?? undefined,
    sourceSystem: entry.sourceSystem ?? undefined,
    version: versionRefOf(entry),
  });
  return {
    constraints: [
      ...c.ontologies.map((o): ControlledTermConfig => ({
        ...common(o),
        sourceType: 'ontology',
        uri: o.uri.getValue() ?? '',
        sourceId: o.acronym,
        ontologyId: o.acronym,
        ontologyName: o.name,
        numTerms: o.numTerms,
      })),
      ...c.branches.map((b): ControlledTermConfig => ({
        ...common(b),
        sourceType: 'ontology-branch',
        sourceId: b.acronym,
        source: b.source,
        branchRootId: b.uri.getValue() ?? '',
        branchRootName: b.name,
        searchDepth: b.maxDepth,
      })),
      ...c.classes.map((t): ControlledTermConfig => ({
        ...common(t),
        sourceType: 'ontology-term',
        sourceId: t.uri.getValue() ?? '',
        ontologyId: t.source,
        source: t.source,
        label: t.label,
        sourceName: t.prefLabel,
        termType: t.type.getJsonValue() as 'OntologyClass' | 'Value',
      })),
      ...c.valueSets.map((v): ControlledTermConfig => ({
        ...common(v),
        sourceType: 'value-set',
        sourceId: v.uri.getValue() ?? '',
        ontologyId: v.vsCollection,
        sourceName: v.name,
        numTerms: v.numTerms,
      })),
    ],
    actions: c.actions.map((a) => ({
      action: a.action,
      termUri: a.termUri.getValue() ?? '',
      sourceUri: a.sourceUri.getValue() ?? '',
      source: a.source,
      type: a.type.getJsonValue() as 'OntologyClass' | 'Value',
      ...(a.to === null ? {} : { to: a.to }),
    })),
  };
}

function defaultOf(field: TemplateField): FieldDefaultValue {
  const descriptor = descriptorOf(paletteTypeOf(field));
  const constraints = (
    field as TemplateField & {
      valueConstraints?: { defaultValue?: unknown; literals?: { label: string; selectedByDefault: boolean }[] };
    }
  ).valueConstraints;
  const value = constraints?.defaultValue;
  if (descriptor.options) {
    const selected =
      constraints?.literals?.filter((option) => option.selectedByDefault).map((option) => option.label) ?? [];
    if (selected.length === 0 && typeof value === 'string' && value !== '') selected.push(value);
    if (selected.length === 0) return { kind: 'none' };
    return descriptor.defaultKind === 'literals'
      ? { kind: 'literals', values: selected }
      : { kind: 'literal', value: selected[0] };
  }
  if (value === null || value === undefined || value === '') return { kind: 'none' };
  if (field.cedarFieldType === CedarFieldType.CONTROLLED_TERM) {
    const term = (field as ControlledTermField).valueConstraints.defaultValue;
    if (term) return { kind: 'iri', iri: term.termUri.getValue() ?? '', label: term.rdfsLabel };
  }
  if (value instanceof Iri) return { kind: 'iri', iri: value.getValue() ?? '', label: null };
  if (typeof value === 'number') return { kind: 'number', value };
  if (typeof value === 'string')
    return descriptor.defaultKind === 'temporal' ? { kind: 'temporal', value } : { kind: 'literal', value };
  return { kind: 'none' };
}

/** A parsed template, as the flat state the designer works in. */
export function toDesignerTemplate(template: Template): DesignerTemplate {
  const fields: Field[] = [];

  template.getChildrenInfo().children.forEach((info, index) => {
    /*
     * `getChild`, not `getField`. A static field's artifact type is
     * `StaticTemplateField` rather than `TemplateField`, and `getField` narrows
     * on that — so it answered null for every page break, section break, rich
     * text block, image and video, and reading a template silently dropped them.
     */
    const child = template.getChild(info.name);
    if (child === null || child.cedarArtifactType === CedarArtifactType.TEMPLATE_ELEMENT) {
      return;
    }
    const field = child as TemplateField;
    const dynamic = info as AbstractDynamicChildDeploymentInfo;

    fields.push({
      id: index + 1,
      artifact: artifactMetadataOf(field),
      valueRecommendationEnabled: dynamic.valueRecommendationEnabled,
      publishedDefinition:
        field.bibo_status === BiboStatus.PUBLISHED
          ? JSON.stringify(CedarWriters.json().getStrict().getFieldWriterForField(field).getAsJsonNode(field))
          : undefined,
      type: paletteTypeOf(field),
      name: field.schema_name ?? info.name,
      deploymentName: info.name,
      status: dynamic.requiredValue ? 'required' : dynamic.recommendedValue ? 'recommended' : 'optional',
      options: optionsOf(field),
      preferredLabel: field.skos_prefLabel ?? undefined,
      alternateLabels: field.skos_altLabel ?? undefined,
      schemaIdentifier: field.schema_identifier ?? undefined,
      language: field.language.getValue() ?? undefined,
      annotations: field.annotations?.getAnnotationNames().map((name) => {
        const annotation = field.annotations!.get(name)!;
        return annotation instanceof AnnotationAtId
          ? { name, kind: 'iri' as const, value: annotation.getAtId() }
          : { name, kind: 'literal' as const, value: (annotation as AnnotationAtValue).getAtValue() };
      }),
      defaultValue: defaultOf(field),
      importedChoiceDefault: allowsOptions(paletteTypeOf(field))
        ? ((field as unknown as { valueConstraints: { defaultValue: string | null } }).valueConstraints.defaultValue ??
          undefined)
        : undefined,
      temporal:
        field.cedarFieldType === CedarFieldType.TEMPORAL
          ? {
              type: (field as TemporalField).valueConstraints.temporalType.getValue() ?? 'xsd:date',
              granularity: (field as TemporalField).temporalGranularity.getValue() ?? 'day',
              timezoneEnabled: (field as TemporalField).timezoneEnabled,
              inputTimeFormat: (field as TemporalField).inputTimeFormat.getValue(),
            }
          : undefined,
      textConstraints:
        field.cedarFieldType === CedarFieldType.TEXT
          ? {
              minLength: (field as TextField).valueConstraints.minLength,
              maxLength: (field as TextField).valueConstraints.maxLength,
              regex: (field as TextField).valueConstraints.regex,
            }
          : undefined,
      numeric:
        field.cedarFieldType === CedarFieldType.NUMERIC
          ? {
              type: (field as NumericField).valueConstraints.numberType.getValue() ?? 'xsd:decimal',
              min: (field as NumericField).valueConstraints.minValue,
              max: (field as NumericField).valueConstraints.maxValue,
              decimalPlaces: (field as NumericField).valueConstraints.decimalPlaces,
              unit: (field as NumericField).valueConstraints.unitOfMeasure,
            }
          : undefined,
      allowMultiple: info instanceof ChildDeploymentInfo ? info.multiInstance : info.isMultiInAnyWay(),
      displayLabel: info.label ?? undefined,
      displayDescription: info.description ?? undefined,
      hidden: info.hidden,
      continuePreviousLine: dynamic.continuePreviousLine ?? false,
      minItems: info.isMultiInAnyWay() ? dynamic.minItems : null,
      maxItems: info.isMultiInAnyWay() ? dynamic.maxItems : null,
      helpText: field.schema_description ?? '',
      content: contentOf(field),
      ...(paletteTypeOf(field) === 'image' || paletteTypeOf(field) === 'youtube'
        ? {
            width: (field as StaticImageField | StaticYoutubeField).width,
            height: (field as StaticImageField | StaticYoutubeField).height,
          }
        : {}),
      atId: field.at_id?.getValue() ?? undefined,
      propertyIri: dynamic.iri ?? undefined,
      controlledTermConstraints: controlledTermConstraintsOf(field),
    });
  });

  return {
    name: template.schema_name ?? '',
    description: template.schema_description ?? '',
    identifier: template.at_id?.getValue() ?? '',
    version: template.pav_version?.getValue() ?? '0.0.1',
    fields,
  };
}

/** Imported conflicts stay visible even when default editing is hidden in preferences. */
export function choiceDefaultConflict(field: Field): string | null {
  if (!allowsOptions(field.type)) return null;
  const values =
    field.defaultValue.kind === 'literal'
      ? [field.defaultValue.value]
      : field.defaultValue.kind === 'literals'
        ? field.defaultValue.values
        : [];
  const all = [
    ...new Set([...values, ...(field.importedChoiceDefault === undefined ? [] : [field.importedChoiceDefault])]),
  ];
  const missing = all.filter((value) => !field.options.includes(value));
  if (missing.length)
    return `The default ${missing.map((value) => '“' + value + '”').join(', ')} is not among the allowed options. Change or clear the default, or add it to the options.`;
  if (field.importedChoiceDefault !== undefined && values.length && !values.includes(field.importedChoiceDefault))
    return `The imported default “${field.importedChoiceDefault}” conflicts with the selected default. Choose a default or clear it to resolve this.`;
  return null;
}

/** Read a first-class field through the model, then reuse the template field mapping. */
export function readField(source: string): Field {
  const text = source.trim();
  if (text.startsWith('{')) {
    const sourceNode = JSON.parse(text);
    const field = CedarReaders.json().getStrict().getTemplateFieldReader().readFromObject(sourceNode).field;
    if (!field.schema_name) throw new Error('The field definition needs a name.');
    const container = CedarBuilders.templateBuilder().withSchemaName('Field import').build();
    container.addChild(field, field.createDeploymentBuilder(field.schema_name).build());
    const document = JSON.parse(JSON.stringify(templateToJson(container)));
    const property = document.properties[field.schema_name];
    if (property.items) property.items = sourceNode;
    else document.properties[field.schema_name] = sourceNode;
    return toDesignerTemplate(readTemplate(JSON.stringify(document))).fields[0];
  }
  const reader = CedarReaders.yaml().getStrict().getTemplateFieldReader();
  const parsed = reader.readFromString(text);
  const deployment = new ChildDeploymentInfo(parsed.field.schema_name ?? '');
  const field = reader.readFromObject(parsed.fieldSourceObject, deployment, new JsonPath()).field;
  if (!field.schema_name) throw new Error('The field definition needs a name.');
  const container = CedarBuilders.templateBuilder().withSchemaName('Field import').build();
  container.addChild(field, deployment);
  return toDesignerTemplate(container).fields[0];
}

/** Validate a reusable specification, including its deployment settings. */
export function validateFieldSpecification(field: Field): void {
  buildTemplate({ name: 'Field validation', description: '', identifier: '', version: '0.0.1', fields: [field] });
}
